# Generated by Django 6.0.4 on 2026-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
